# netlify.toml (in monorepo root)

[build]
  base    = "frontend/"       # Build context
  command = "npm i && npm run build"   # Build command within frontend/


[build.environment]
   # Set non-secret build vars if needed
   # NODE_VERSION = "18"