# netlify.toml (in monorepo root)

[build]
  base    = "frontend/"       # Build context
  command = "npm i && npm run build"   # Build command within frontend/
  publish = "frontend/.netlify/" # Explicit publish dir (path from repo root)

# You might not need functions dir setting if preset handles it
# [functions]
#  directory = ".netlify/functions/" # Relative to base

[build.environment]
   # Set non-secret build vars if needed
   # NODE_VERSION = "18"