# netlify.toml (in monorepo root) - Attempt 4

[build]
  # Run build commands from frontend directory
  base    = "frontend/"
  # Build command
  command = "npm run build"
  # *** POINT TO THE ADAPTER'S EXPECTED OUTPUT DIRECTORY ***
  # The Remix Netlify adapter usually creates a .netlify folder
  # within the 'base' directory.
  publish = "build" 

# OMIT [functions] block - Let the adapter and Netlify figure it out
# from the structure within the publish directory.