# netlify.toml (Place in monorepo root)

[build]
  # Base directory for the build context
  base    = "frontend/"
  # Command to run inside the base directory
  command = "pwd && ls && npm i && CI=false npm run build"