"""Add model_id to conversations table

Revision ID: 6201bc17813d
Revises: a5c8a107a074
Create Date: 2025-04-16 10:06:36.598713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6201bc17813d'
down_revision: Union[str, None] = 'a5c8a107a074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('model_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_model_id'), 'conversations', ['model_id'], unique=False)

    # Set default value for existing records
    op.execute("UPDATE conversations SET model_id = 'meta-llama/Llama-3.3-70B-Instruct-Turbo-Free' WHERE model_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_model_id'), table_name='conversations')
    op.drop_column('conversations', 'model_id')
    # ### end Alembic commands ###
