"""Add uploaded_documents table and related_doc_id to messages

Revision ID: 8a2d6f24c699
Revises: 97d997bbe11a
Create Date: 2025-04-11 13:53:06.979869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2d6f24c699'
down_revision: Union[str, None] = '97d997bbe11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('related_doc_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_related_doc_id'), 'messages', ['related_doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_related_doc_id'), table_name='messages')
    op.drop_column('messages', 'related_doc_id')
    # ### end Alembic commands ###
