"""Add uploaded_documents table and related_doc_id to messages

Revision ID: 97d997bbe11a
Revises: ee1069e6e0b8
Create Date: 2025-04-11 13:29:23.537969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d997bbe11a'
down_revision: Union[str, None] = 'ee1069e6e0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_documents_conversation_id'), 'uploaded_documents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_uploaded_documents_doc_id'), 'uploaded_documents', ['doc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_documents_doc_id'), table_name='uploaded_documents')
    op.drop_index(op.f('ix_uploaded_documents_conversation_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    # ### end Alembic commands ###
